name: Simple Deploy via sshpass

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js & Cache npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build

      - name: Install sshpass
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass

      - name: Copy build and necessary files to server
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" \
            scp -o StrictHostKeyChecking=no -r \
            dist prisma package.json package-lock.json .env \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/www/wwwroot/VorPlay

      - name: Remote Deploy Commands
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
            "set -e && \
            cd /www/wwwroot/VorPlay && \
            echo '--- Instalando dependências de produção ---' && \
            npm ci --production && \
            echo '--- Gerando Prisma Client ---' && \
            npx prisma generate && \
            echo '--- Aplicando migrações Prisma ---' && \
            npx prisma migrate deploy && \
            echo '--- Reiniciando PM2 ---' && \
            pm2 restart VorPlay || pm2 start dist/main.js --name VorPlay"
